<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\lumidex-icon.ico</ApplicationIcon>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="AvaloniaDialogs" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DialogHost.Avalonia" />
    <PackageReference Include="Flurl" />
    <PackageReference Include="Flurl.Http" />
    <PackageReference Include="Humanizer" />
    <PackageReference Include="LinqKit" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="ObservableCollectionEx" />
    <PackageReference Include="Optris.Icons.Avalonia.MaterialDesign" />
    <PackageReference Include="Optris.Icons.Avalonia.FontAwesome" />
    <PackageReference Include="ScottPlot" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Xaml.Behaviors" />

    <!-- Dev -->
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="HotAvalonia" PrivateAssets="All" Publish="True" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" VersionOverride="$(AvaloniaVersion)" PrivateAssets="All" Publish="True" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumidex.Core\Lumidex.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Features\MainSearch\MainSearchView.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\lumidex-icon.ico" />
  </ItemGroup>
  
</Project>
