name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

 
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: read
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION }}
      - name: Build
        run: dotnet build ${{ env.SOLUTION }} -c Release --no-restore
      - name: Test
        run: dotnet test ${{ env.SOLUTION }} -c Release --no-build
