name: Installer

on: workflow_dispatch


env:
  PROJECT: Lumidex.Desktop/Lumidex.Desktop.csproj
  ISCC: C:\Program Files (x86)\Inno Setup 6\ISCC.exe

jobs:
  installer:
    runs-on: [self-hosted, windows, x64]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore
        run: dotnet restore ${{ env.PROJECT }}
      - name: Tools
        run: dotnet tool restore
      - name: Publish
        run: dotnet publish ${{ env.PROJECT }} -r win-x64 --self-contained -c Release -o publish-win
      - name: Version
        run: dotnet tool run nbgv get-version
      - name: Version Variable
        run: $VERSION = (dotnet tool run nbgv get-version)[3].Split(":")[1].Trim()
      - name: Installer
        run: "& '${{ env.ISCC }}' lumidex-installer-win.iss /DMyAppProductVersion=$env:VERSION"
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v3.1.3
        with:
          connection_string: ${{ secrets.INSTALLERBLOBCONNECTIONSTRING }}
          fail_if_source_empty: true
          is_recursive: true
          container_name: installers
          source_folder: dist\
          destination_folder: \