# Create the macos app bundle and attach it to the release for this tag.
# This workflow runs on release tags by creating a release on github.

name: Create and Upload MacOS App Bundle

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: Lumidex
  PROJECT: Lumidex.Desktop/Lumidex.Desktop.csproj
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
  
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ${{ env.PROJECT }}

      - name: Build the App Bundle
        run: |
          VERSION=(dotnet tool run dotnet-gitversion /showvariable SemVer)
          chmod +x scripts/package-macos-app.sh
          scripts/package-macos-app.sh $VERSION

      - name: Upload app bundle
        uses: actions/upload-artifact@v4
        with:
          name: lumidex-app-bundle
          path: dist/Lumidex*.app.zip
          retention-days: 7

      # - name: Upload to release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release upload ${GITHUB_REF_NAME} .\dist\Lumidex-*.app.zip