# Create the windows installer and attach it to the release for this tag.
# This workflow runs on release tags by creating a release on github.

name: Create and Upload Windows Installer

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT: Lumidex.Desktop/Lumidex.Desktop.csproj

jobs:
  windows-installer:
    runs-on: [self-hosted, windows, x64]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore
        run: dotnet restore ${{ env.PROJECT }}
      - name: Tools
        run: dotnet tool restore
      - name: Publish
        run: dotnet publish ${{ env.PROJECT }} -r win-x64 --self-contained -c Release -o publish-win
      - name: Show Version
        run: dotnet tool run dotnet-gitversion
      - name: Installer
        run: |
          $VERSION=(dotnet tool run dotnet-gitversion /showvariable SemVer)
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' lumidex-installer-win.iss /DMyAppProductVersion=${VERSION}
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $env:GITHUB_REF_NAME (Get-Item .\dist\win\Lumidex-*.exe).FullName